### ISSUE TITLE
Some songs Not Playing/Downloading

### ISSUE THREAD

**Issue by anxiouslelimo** [mostafaalagamy/Metrolist#174]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Try to play/download https://youtu.be/zZ5QzR4Nk18 or https://youtu.be/5NosYGbaOio

### Expected behavior

Songs should play/download

### Actual behavior

Unknown Error or Timed Out/Download Failed.

### Logs

NIL

### Metrolist version

10.6.0

### Android version

Android 14

**Comment by mostafaalagamy** [comment]
> Try to play/download https://youtu.be/zZ5QzR4Nk18 or https://youtu.be/5NosYGbaOio

They're working fine, and the download went smoothly too!

**Comment by ghost** [comment]
Forgot to add that it is when logged out. 

https://github.com/user-attachments/assets/9b69a9c7-ed2f-4e59-a8cc-e4476d85ff77

**Comment by mostafaalagamy** [comment]
Let me know if the issue has been resolved.

**Comment by ghost** [comment]
The issue is solved. Requesting a hotfix release.

**Comment by ImpenetrableNoble** [comment]
#113 

@mostafaalagamy It's not resolved because I’ve been experiencing an ongoing issue with offline playback on Metrolist, where songs fail to play even when my Wi-Fi connection and VPN service are both turned off. This problem has persisted for several weeks now, and I believe it may be related to a potential issue with the YouTube Music API server or its handling of offline playback functionality.

If you're using the official YouTube music API that might be the issue then, try using this instead:

https://github.com/sigma67/ytmusicapi

This is the customized version of YouTube music API but it's the unofficial version. You're welcome.

**Comment by Rinoa919** [comment]
Not playing again

**Comment by Rinoa919** [comment]
Not playing

![Image](https://github.com/user-attachments/assets/9fbd8f18-a785-4971-9b85-a31bdfaa2e30)

**Comment by mostafaalagamy** [comment]
Try latest build!

**Comment by Rinoa919** [comment]
My app is updated

![Image](https://github.com/user-attachments/assets/1a764ee7-e6d2-4fcc-910c-64f69ce2fb53)

**Comment by mostafaalagamy** [comment]
> My app is updated
> 
> ![Image](https://github.com/user-attachments/assets/1a764ee7-e6d2-4fcc-910c-64f69ce2fb53)

Fixed in latest debug build!

**Comment by Rinoa919** [comment]
Where i can download the latest debug?

**Comment by Rinoa919** [comment]
Not Working again

![Image](https://github.com/user-attachments/assets/49f01116-f89a-447f-8852-de65ec3e9385)

**Comment by mostafaalagamy** [comment]
> Where i can download the latest debug?

https://github.com/mostafaalagamy/Metrolist/actions/runs/21490806758

Clear cache!

**Comment by Rinoa919** [comment]
Still dont play bro

**Comment by mostafaalagamy** [comment]
> Still dont play bro

Clear cache or data please!!

**Comment by Rinoa919** [comment]
Look at this even i delete it still cant play

![Image](https://github.com/user-attachments/assets/f3e2969b-e834-4467-9bf3-df36fb43bf3a)

**Comment by mostafaalagamy** [comment]
> Look at this even i delete it still cant play

I want a screenshot from the player settings!

**Comment by Rinoa919** [comment]
This one? What kind of player settings?

![Image](https://github.com/user-attachments/assets/57671962-59d7-437d-bafd-70d1d884ddeb)

**Comment by mostafaalagamy** [comment]
> This one? What kind of player settings?

This's not latest debug build! And you don't want to help me so that I can help you!

The issue solved in the last commit. Wait for the next update!

**Comment by Rinoa919** [comment]
Sorry so how can i install the latest debug? Give ne tutorial

**Comment by mostafaalagamy** [comment]
> Sorry so how can i install the latest debug? Give ne tutorial

https://github.com/mostafaalagamy/Metrolist/actions/runs/21490806758

Open this link in your browser and download release or debug .zip file, Then install the build and clear the cache!

**Comment by Rinoa919** [comment]
How to install look

![Image](https://github.com/user-attachments/assets/9edf48a8-a886-40c8-b704-1a23c315e88f)

**Comment by mostafaalagamy** [comment]
> How to install look
> 
> ![Image](https://github.com/user-attachments/assets/9edf48a8-a886-40c8-b704-1a23c315e88f)

Open build release (gsm), You will find the APK file

**Comment by Rinoa919** [comment]
No apk

![Image](https://github.com/user-attachments/assets/a0ad83ba-0a13-42c1-8c0c-4e6df5dd2b5a)

**Comment by mostafaalagamy** [comment]
> No apk
> 
> ![Image](https://github.com/user-attachments/assets/a0ad83ba-0a13-42c1-8c0c-4e6df5dd2b5a)

You can search for how to install or extract this files.

**Comment by Rinoa919** [comment]
Still no apk im confuse

**Comment by mostafaalagamy** [comment]
> Still no apk im confuse

Use MT Manager app

**Comment by Rinoa919** [comment]
What mt? Look this

![Image](https://github.com/user-attachments/assets/f0cd6077-0091-4669-96a2-becc67ed4311)

**Comment by Rinoa919** [comment]
Still wont work can i ask when do u update the your app?

**Comment by mostafaalagamy** [comment]
> Still wont work 

If you were able to extract the files, try this version.

https://github.com/mostafaalagamy/Metrolist/actions/runs/21499766383

**Comment by uzuki-P** [comment]
> > Still wont work
> 
> If you were able to extract the files, try this version.
> 
> [mostafaalagamy/Metrolist/actions/runs/21499766383](https://github.com/mostafaalagamy/Metrolist/actions/runs/21499766383)

The debug version actually fix it for me. But the release version is still not work. Will wait for the next update. Thanks

**Comment by Rinoa919** [comment]
Sorry still no apk look

![Image](https://github.com/user-attachments/assets/d534a100-84bf-42cf-bff7-c9f776d5106b)

**Comment by uzuki-P** [comment]
> Sorry still no apk look
> 
> ![Image](https://github.com/user-attachments/assets/d534a100-84bf-42cf-bff7-c9f776d5106b)

Download the debug artifact (top one), or just wait for the next update

<img width="666" height="396" alt="Image" src="https://github.com/user-attachments/assets/86fa92d8-3c9b-4e71-ba8e-1546447210c0" />

**Comment by Rinoa919** [comment]
I already download ALL TXT format STILL NO APK
i think i will shift to Simpmusic
