### ISSUE TITLE
Unknown Error persists on 11.2.0

### ISSUE THREAD

**Issue by maytresha** [mostafaalagamy/Metrolist#414]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [x] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

It occurs after playing second or third song post launching the app. It is triggered either after the first song is finished or by pressing Shuffle.

### Expected behavior

To continue playing normally.

### Actual behavior

![Image](https://github.com/user-attachments/assets/58ea879d-cafe-41aa-9487-d980100e8c8b)

### Logs

Regular app has no Export Log.

### Metrolist version

11.2.0

### Android version

14.0

**Comment by mostafaalagamy** [comment]
Clean install?

**Comment by maytresha** [comment]
> Clean install?

yessir...

**Comment by mostafaalagamy** [comment]
> > Clean install?
> 
> yessir...

![Screenshot_2025-03-27-04-17-35-967_com.metrolist.music.jpg](https://github.com/user-attachments/assets/6984cd06-eb97-4e23-b532-b13aa6179832)

Works fine with me!

**Comment by maytresha** [comment]
Yeah, it's not particularly track-based. I have similar-styled loading issue in RiMusic, so IDK, maybe a region-specific or ISP-based issue. Any way to export log?

**Comment by zettaexa** [comment]
Still doesn't work for me, considering just moving to previous version again since i already updated my playlists :(

**Comment by zettaexa** [comment]
I can do some testing with different app versions by commit to prob fix which one was faulty

**Comment by owenconnorz** [comment]
@zettaexa Found a issue that can cause it and its to do with setting the audio quality to max this caused a issue for me so I set it back to high and music was working again.

**Comment by CaptechOmar** [comment]
> [@zettaexa](https://github.com/zettaexa) Found a issue that can cause it and its to do with setting the audio quality to max this caused a issue for me so I set it back to high and music was working again.

OMG
So that was it from the beginning?

**Comment by L0lly69** [comment]
> [@zettaexa](https://github.com/zettaexa)Menemukan masalah yang dapat menyebabkan hal itu dan itu ada hubungannya dengan pengaturan kualitas audio ke maksimal. Hal ini menyebabkan masalah bagi saya, jadi saya mengaturnya kembali ke tinggi dan musik pun berfungsi lagi.

you're right.. I also changed the sound quality to high and it runs normally... but there is still one problem' when playing music in the background sometimes turns off by itself

**Comment by m-obeid** [comment]
Other players like OuterTune seem to be facing similar issues too right now

**Comment by m-obeid** [comment]
Also the "This video may be inappropriate for some users" error persists, I think it is related to that too.

**Comment by Luca-blip2** [comment]
I am having this problem with explicit songs

**Comment by L0lly69** [comment]
I already found a solution for an unknown error.. with vpn all songs no problem

**Comment by L0lly69** [comment]
even all songs that previously failed to play with vpn become playable

**Comment by Luca-blip2** [comment]
> even all songs that previously failed to play with vpn become playable

But did you have the problem for explicit song not being playable?

**Comment by L0lly69** [comment]
> > bahkan semua lagu yang sebelumnya gagal diputar dengan vpn menjadi dapat diputar
> 
> Tetapi apakah Anda mengalami masalah karena lagu eksplisit tidak dapat diputar?

yes... all explicit songs failed to play with vpn successfully

**Comment by L0lly69** [comment]
![Image](https://github.com/user-attachments/assets/d5236f86-f674-4626-ad9a-83e9c520bc87)

**Comment by owenconnorz** [comment]
Yes I have issues with music being cut off and also issues with downloading some songs.

**Comment by Luca-blip2** [comment]
Even with VPN I still can't listen explicit songs

**Comment by L0lly69** [comment]
> Ya, saya mengalami masalah dengan musik yang terputus dan juga masalah saat mengunduh beberapa lagu.

try using a vpn.. previously I also faced the same problem but by using a vpn all the problems were resolved

**Comment by L0lly69** [comment]
> Bahkan dengan VPN saya masih tidak bisa mendengarkan lagu eksplisit

try logging out of your YM account and clearing your data.. after that there is no need to login YM account.I also play songs without login YM account

**Comment by Luca-blip2** [comment]
> 
> try logging out of your YM account and clearing your data.. after that there is no need to login YM account
 
I logged out and cleared data but still not working. I believe it's necessary to log in for age verification but even if I do it doesn't work

**Comment by Luca-blip2** [comment]
The weird thing is if I log in and play the explicit song from within the YouTube music website that opens automatically, it works. It's on Metrolist the issue

**Comment by L0lly69** [comment]
> > coba log out akun YM anda dan clear data.. setelah itu tidak perlu login akun YM lagi
> 
> Saya keluar dan menghapus data tetapi tetap tidak berfungsi. Saya yakin perlu masuk untuk verifikasi usia tetapi meskipun saya melakukannya, itu tidak berfungsi

it's weird because I had the same problem before.but I can make it my way

**Comment by anuragtyagi-dev** [comment]
Yeah , opting music quality to High from Max (beta) does solves this " unknown error " issue. It's weird but 11.0.0v was able to play all songs with Max audio quality ( for me ).

**Comment by anuragtyagi-dev** [comment]
@Luca-blip2 I think you should try re-installing or clean installing and then first login with your account and set audio to high then play , working for me with explicit songs with high audio quality, Max ( beta ) is having issues.

**Comment by maytresha** [comment]
True, while High instead of Max fixes the Unknown Error, the app still simply fails to play some tracks (stays at 0:00 without Error) and crashes on some other tracks.

**Comment by maytresha** [comment]
As such, user owencz1998 resolved the Unknown Error by suggesting changing audio quality from Max to High.

**Comment by mostafaalagamy** [comment]
> As such, user owencz1998 resolved the Unknown Error by suggesting changing audio quality from Max to High.

I would like to remove the Max quality option.

**Comment by zettaexa** [comment]
> > As such, user owencz1998 resolved the Unknown Error by suggesting changing audio quality from Max to High.
> 
> I would like to remove the Max quality option.

Im wondering what does max do? is it just High again?
